### ISSUE TITLE
Stack trace when creating new project?

### ISSUE THREAD

**Issue by sbidoul** [acsone/weblate-odoo-component-generator#14]
Caught by sentry following the weblate upgrade.

AttributeError: 'Project' object has no attribute 'mail'

![image](https://user-images.githubusercontent.com/692075/196157229-60a8a2be-b024-4fe0-87fb-69e298557ad3.png)

**Comment by sbidoul** [comment]
cc/ @remi-filament

**Comment by remi-filament** [comment]
mail was removed in https://github.com/WeblateOrg/weblate/commit/2e812704d7c77d5509d24b4c95074735869a8e69
